[1단계 - 사다리 생성] 이준섭 미션 제출합니다.
poi1649/java-ladder pull request #1
Opened 2024-02-01 21:47 UTC by junseoplee

2024-02-02 13:33 UTC, poi1649 requested changes
사다리 어떠셨나요? 저는 처음 할 때 굉장히 어려웠습니다ㅋㅋㅋㅋ
고생 많으셨습니다. 커밋 메시지 하나하나에서 TDD를 하려고 노력한 게 보여서 너무 아름답네요.. 🥲 👍
대부분의 리뷰는 커멘트로 남겼고, 남길 장소가 애매한 리뷰 밑에 추가합니다!
반영 후 리뷰 재요청은 월요일 6시까지 주세요(빨리 하면 더 빨리 리뷰해줌), 

++ 이번엔 다다음주 금요일 오후 6시 전에 2단계 첫 리뷰 요청을 완료해야한다. 라는 요구사항을 추가해보려고 하니, 참고해주세요.

---

저는 `기능단위커밋` == `요구사항의 한 줄을 통째로 포함하는 것` 이라고 이해하고 있어요. 
<img width="385" alt="스크린샷 2024-02-02 오후 9 35 01" src="https://github.com/poi1649/java-ladder/assets/74969077/8c74b9db-7a87-4271-9880-b92ca6c3414e">
위의 세 커밋을 합쳐서 File changed 탭을 확인하면 다음과 같은 목록이 나옵니다.

<img width="305" alt="스크린샷 2024-02-02 오후 9 35 08" src="https://github.com/poi1649/java-ladder/assets/74969077/29af9947-c1fb-4516-90ea-90af52b7d8d7">

어떤가요? 
(작성해주신 요구사항과는 약간 차이가 있지만) `참여자들의 이름을 검증하는 기능 추가` 한 줄의 메시지로 표현할 수 있을 것 같지 않나요?

이런식으로 합쳐서 커밋을 해주시면 코드를 읽는 입장에서도, 그렇고 만약 해당 기능을 롤백해야하는 일이 생겼을 때 테스트까지 한 번에 삭제할 수도 있죠! (테스트만 남아있거나, 프로덕션만 남아있을 경우 괜한 컴파일 에러가 발생하겠죠?)

저는 이런 이점때문에 저런 단위의 커밋을 선호합니다. 
하지만 당연히 정답은 없고, 확실한 근거를 가지고 작업하는 것이 제일 중요합니다. 그런 의미에서 혹시 커밋 단위를 정한 근거를 공유해줄 수 있나요?

2024-02-02 13:33 UTC, poi1649 commented on README.md
> +    - [x] 가로 라인의 폭은 5칸이다.
체크박스 형태로 요구사항을 정리한 거 좋네요 👍

다만 커밋 기록을 보니까, 한 번에 모든 요구사항을 다 체크한 것 같아요ㅋㅋㅋ 하나씩 해결해가면서 문서도 계속해서 업데이트해주면 내가 뭘 빠뜨리고 있고, 뭘 다음에 해야할 지 더 정하기 쉬워질 수 있습니다! 요구사항 문서 업데이트까지 기능단위 커밋의 한 부분으로  볼 수도 있어요

2024-02-02 13:33 UTC, poi1649 commented on build.gradle
> +        languageVersion = JavaLanguageVersion.of(17)
👍👍

2024-02-02 13:33 UTC, poi1649 commented on gradle/wrapper/gradle-wrapper.properties
> +validateDistributionUrl=true
이건 무슨 설정일까요!?

2024-02-02 13:33 UTC, poi1649 commented on src/main/java/laddergame/controller/LadderGameController.java
> +
create와 generate의 구별 기준은 뭔가요!?

2024-02-02 13:33 UTC, poi1649 commented on src/main/java/laddergame/controller/LadderGameController.java
> +  }
패키지 구분을 보니 Participants라는 클래스는 도메인에 포함된다고 생각하신 것 같네요!
그런데, Controller에서 생성해주신 이유가 있나요? 이렇게 만들었을 때 장단점은 뭐고, Layered Architecture에서 Controller 의 역할은 뭘까요?

2024-02-02 13:33 UTC, poi1649 commented on src/main/java/laddergame/model/ErrorMessage.java
> +  NOT_IN_RANGE_HEIGHT("[ERROR] 사다리의 높이는 2 이상이어야 합니다.");
오 enum으로 예외를 관리하게 된 이유가 뭘까요? 어떤 장점이 있나요?

추가로, ERROR 라는 메시지의 PREFIX는 별도의 상수로 관리해도 좋겠네요.

2024-02-02 13:33 UTC, poi1649 commented on src/main/java/laddergame/model/LadderGenerator.java
> +            .toList()
오호 인트스트림.. 

저는 스트림의 장점을 다음과 같이 봅니다.
1. 컬렉션 내부 요소 수정없이 재활용 가능(원본 요소의 불변성 유지)
2. 복잡한 로직을 함수형으로 표현 가능(가독성 향상)
3. 반복문에 병렬성 쉽게 부여 가능

그런데 지금은 일단 스트림의 요소 값(0에서 사다리 높이까지의 숫자) 은 사용되고 있지 않으니 1번 장점은 없고, 병렬성도 없으니 3번 장점도 없습니다.
그럼 이제 가독성만이 스트림의 사용 이유일 것 같아요. 그런데 밑처럼 일반 포문을 사용하는게 어떤 기능인지가 더 명확해보이지 않나요!?🧐
 
```suggestion
List<Rung> rungs = new ArrayList<>();
for (int i = 0; i < height.getHeight(); i++) {
    rungs.add(new Rung(participants, rungCreateDecider));
}
```

스트림도 생성 비용이나 디버깅등에서 단점이 있기에 사용의 기준을 명확하게 결정하고 사용하는게 좋습니다!
이 기회에 스트림의 장단점 한 번 정리해보시죠👍

2024-02-02 13:33 UTC, poi1649 commented on src/main/java/laddergame/model/ladder/Height.java
> +  public Height(int receivedHeight) {
메서드와 필드 사이 공백이 필요해요!

2024-02-02 13:33 UTC, poi1649 commented on src/main/java/laddergame/model/ladder/Rung.java
> +    int pointCount = participants.getParticipants().size() - 1;
pointCount보다 사다리의 넓이를 표현할 수 있는 더 적합한 말이 있으면 좋을 것 같아요

2024-02-02 13:33 UTC, poi1649 commented on src/main/java/laddergame/model/participant/Participant.java
> +      throw new IllegalArgumentException(ErrorMessage.NOT_IN_RANGE_PARTICIPANT_NAME.getMessage());
<img width="498" alt="스크린샷 2024-02-02 오후 10 17 43" src="https://github.com/poi1649/java-ladder/assets/74969077/e58648c6-fbf6-4273-9c12-5063aecafe25">

5자인데 에러가 납니다.🥲

2024-02-02 13:33 UTC, poi1649 commented on src/main/java/laddergame/view/LadderStandard.java
> +
오... enum으로 관리 너무 좋네요. 패키지도 view에 있는 디테일 💯💯

2024-02-02 13:33 UTC, poi1649 commented on src/test/java/laddergame/model/participant/ParticipantsTest.java
> +        .toList();
아주 적절한 스트림 사용이네요👍

2024-02-02 13:33 UTC, poi1649 commented on src/test/java/laddergame/model/LadderGeneratorTest.java
> +  }
오호 테스트 객체를 따로 만들어서 랜덤성을 제거했네요 👍👍👍 어디서 보셨는진 모르겠지만 아주아주 훌륭합니다.

---

소소한 질문!

1. 리스트의 맨 앞의 요소를 제거할 때 ArrayList vs LinkedList 각각 어떤게 시간복잡도를 가지나요?
2. 만약 RungCreaterDecider 의 다른 필드나 메서드에 접근하지 못하게하려면 (실제로 프로덕트 개발을 하다보면, 테스트에서 외부 의존성을 끊기위해 프로덕션 코드 자체에 접근을 막아야 될 경우도 생깁니다.) 어떻게 수정해볼 수 있을까요?

2024-02-02 13:33 UTC, poi1649 commented on src/test/java/laddergame/model/ladder/RungTest.java
> +  }
별도의 클래스로 분리하면 중복을 줄일 수도 있겠네요👍

2024-02-02 14:45 UTC, junseoplee commented
> 사다리 어떠셨나요? 저는 처음 할 때 굉장히 어려웠습니다ㅋㅋㅋㅋ 고생 많으셨습니다. 커밋 메시지 하나하나에서 TDD를 하려고 노력한 게 보여서 너무 아름답네요.. 🥲 👍 대부분의 리뷰는 커멘트로 남겼고, 남길 장소가 애매한 리뷰 밑에 추가합니다! 반영 후 리뷰 재요청은 월요일 6시까지 주세요(빨리 하면 더 빨리 리뷰해줌),
> 
> ++ 이번엔 다다음주 금요일 오후 6시 전에 2단계 첫 리뷰 요청을 완료해야한다. 라는 요구사항을 추가해보려고 하니, 참고해주세요.
> 
> 저는 `기능단위커밋` == `요구사항의 한 줄을 통째로 포함하는 것` 이라고 이해하고 있어요. <img alt="스크린샷 2024-02-02 오후 9 35 01" width="385" src="https://private-user-images.githubusercontent.com/74969077/301845942-8c74b9db-7a87-4271-9880-b92ca6c3414e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4ODQzMTIsIm5iZiI6MTcwNjg4NDAxMiwicGF0aCI6Ii83NDk2OTA3Ny8zMDE4NDU5NDItOGM3NGI5ZGItN2E4Ny00MjcxLTk4ODAtYjkyY2E2YzM0MTRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDE0MjY1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkNjM2NjhhNTUwN2Y2MjQyZGMwNzY2MTg1ZTk0YThmMTAwYmQxMjlkNjJiNzU5ZGE2ODEzMjZlYzZkNjI2OTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WaXRh0OUYz3DIRayYw6yGVxtIpyNBzCzZwX6LUpZxa8"> 위의 세 커밋을 합쳐서 File changed 탭을 확인하면 다음과 같은 목록이 나옵니다.
> 
> <img alt="스크린샷 2024-02-02 오후 9 35 08" width="305" src="https://private-user-images.githubusercontent.com/74969077/301845964-29af9947-c1fb-4516-90ea-90af52b7d8d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4ODQzMTIsIm5iZiI6MTcwNjg4NDAxMiwicGF0aCI6Ii83NDk2OTA3Ny8zMDE4NDU5NjQtMjlhZjk5NDctYzFmYi00NTE2LTkwZWEtOTBhZjUyYjdkOGQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDE0MjY1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlYTRjZjJjY2I1NTYwMTNhMDg2Yjg4NTkwM2RhYThlZTQzMWI3ZGY3MjA0OTUxYWU0ZDdhOGQ2OTYzOGQ0Y2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._PXmEfJjUxYInUUs-7auVsT-7b5hNcZrZ7dzKATbJ9U">
> 어떤가요? (작성해주신 요구사항과는 약간 차이가 있지만) `참여자들의 이름을 검증하는 기능 추가` 한 줄의 메시지로 표현할 수 있을 것 같지 않나요?
> 
> 이런식으로 합쳐서 커밋을 해주시면 코드를 읽는 입장에서도, 그렇고 만약 해당 기능을 롤백해야하는 일이 생겼을 때 테스트까지 한 번에 삭제할 수도 있죠! (테스트만 남아있거나, 프로덕션만 남아있을 경우 괜한 컴파일 에러가 발생하겠죠?)
> 
> 저는 이런 이점때문에 저런 단위의 커밋을 선호합니다. 하지만 당연히 정답은 없고, 확실한 근거를 가지고 작업하는 것이 제일 중요합니다. 그런 의미에서 혹시 커밋 단위를 정한 근거를 공유해줄 수 있나요?

클래스 단위 기능 구현을 커밋 단위로 정했어요. 
우선 클래스에서 구현할 기능을 먼저 정리하고 테스트 코드를 파일 단위로 구현 후 커밋합니다.
이후 클래스를 구현하고 구현에 필요한, 관련된 파일들을 함께 커밋했습니다.
이렇게 되면 경우에 따라 세부 내용이 많아질 수 있어서 커밋 단위를 더 작게 해야겠다고 생각했습니다.

2024-02-02 14:47 UTC, junseoplee commented on README.md
> +    - [x] 가로 라인의 폭은 5칸이다.
맞아요 요구사항은 생각 못하고 커밋하다가 중간에 생각났어요.
기능 단위 커밋에 관련된 파일 및 요구사항까지 한번에 커밋하면 되겠죠!

2024-02-02 14:49 UTC, junseoplee commented on gradle/wrapper/gradle-wrapper.properties
> +validateDistributionUrl=true
설정을 바꾸고 업데이트하면서 자동으로 변경된 파일 같아요! 맨 마지막에 보니까 이렇게 변경된 파일들이 꽤 있어서 [fix: 불필요한 파일 삭제 및 수정] 이렇게 한번에 정리했습니다.

2024-02-02 15:21 UTC, junseoplee commented on src/main/java/laddergame/controller/LadderGameController.java
> +
참여자 입력 및 높이 입력과 같이 사용자가 능동적으로 행하는 기능을 create로 정했어요.
generate는 사용자 입장에서 보면 입력한 값을 가지고 수동적으로 자동으로 생성되기 때문에 구별했습니다. generate는 재료(참여자, 높이)를 모아 만드는 느낌이 있다 생각했거든요.
하지만 이것은 저의 생각이고 이러한 설명이 없다면 헷갈릴 수 있겠다 생각이드네요!
create를 receive로 변경했습니다!

2024-02-02 21:56 UTC, junseoplee commented on src/main/java/laddergame/controller/LadderGameController.java
> +  }
컨트롤러는 모델과 뷰로 명령을 전달합니다. 사용자와 비즈니스 로직 간의 통신을 관리합니다.
각 모델과 뷰에서 담당하는 기능을 한 곳에서 컨트롤 하기 위해 이렇게 구성했습니다.
입력 자체는 인풋뷰 클래스에서 처리하고 해당 객체를 생성하는 역할만 컨트롤러에서 담당합니다.
생성된 객체를 이용하여 사다리를 생성합니다. 이것은 뷰와 모델을 연결하는 역할을 합니다.
하지만 의존성이 너무 집중되어 있다는 단점이 있습니다. 클래스를 수정할 때 영향을 받을 수 있습니다.
따라서 필요로 하는 의존 객체를 주입하는 식으로 변경했습니다.
객체 수정 시, 분리 되어있는 객체의 필요한 부분만 수정하며 유연성이 증가합니다.

2024-02-02 22:18 UTC, junseoplee commented on src/main/java/laddergame/model/ErrorMessage.java
> +  NOT_IN_RANGE_HEIGHT("[ERROR] 사다리의 높이는 2 이상이어야 합니다.");
예외 상황을 명확하게 정의하고 설명할 수 있습니다. 추가로 확장성과 변경 용이성이 있습니다.

2024-02-02 22:28 UTC, junseoplee commented on src/main/java/laddergame/model/LadderGenerator.java
> +            .toList()
for문을 쓸까 고민했습니다! 
스트림은 아직 익숙하지 않은 방식이기 때문에 조금 더 써보기 위해 스트림을 사용했습니다.
확실히 이 코드에서 스트림의 장점은 가독성 밖에 없고 이 마저도 for문이 더 명확해보입니다.
스트림은 데이터의 흐름을 처리합니다. 간결하고 직관적인 표현이 가능합니다. 다양한 연산이 있고, 병렬처리가 가능합니다.
원본 데이터를 변경하지 않고 별도로 생성합니다. 따라서 정렬이나 필터링 작업도 별도에서 처리되며 원본 데이터가 변경되지 않습니다.
스트림을 열면 생성 비용이 들기 때문에 무분별한 사용 보다는 상황을 고려하는 것이 좋으며, 순서를 보장해야할 때는 병렬성이 단점이 될 수도 있습니다.

2024-02-02 22:42 UTC, junseoplee commented on src/main/java/laddergame/model/ladder/Rung.java
> +    int pointCount = participants.getParticipants().size() - 1;
해당 지점에 rung(가로 줄)이 있다면 건너뛰는 것이 목적이기 때문에 총 포인트가 몇 개 있냐를 보기 위해 pointCount라는 변수명을 채택했습니다. 
물론 포인트 말고 step 같은 표현을 쓸 수도 있겠네요.

2024-02-02 22:49 UTC, junseoplee commented on src/main/java/laddergame/model/participant/Participant.java
> +      throw new IllegalArgumentException(ErrorMessage.NOT_IN_RANGE_PARTICIPANT_NAME.getMessage());
최대 높이를 입력 받는 메서드에서는 공백을 제거하는 trim()을 넣었는데 참여자의 이름을 입력 받는 메서드에서는 빼먹었네요!

2024-02-02 23:08 UTC, junseoplee commented on src/test/java/laddergame/model/LadderGeneratorTest.java
> +  }
1. ArrayList에서 맨 앞 요소를 제거할 때는 remove(0)을 사용해서 제거합니다.
이 경우 모든 요소가 한 칸씩 앞으로 이동하겠네요. 시간 복잡도는 요소의 수 만큼 있습니다.
LinkedList에서 맨 앞 요소를 제거할 때는 포인터 간의 연결을 끊으면 되기 때문에 그 시간 만큼만 걸립니다.
2. Mock 객체를 사용해볼 수 있습니다.

2024-02-03 08:37 UTC, poi1649 approved these changes

2024-02-03 08:37 UTC, poi1649 commented on README.md
> +    - [x] 가로 라인의 폭은 5칸이다.
물음표를 느낌표로 잘못친건가요? 아니면 깨달음의 표시인가요ㅋㅋㅋㅋ 질문이라면 저는 그렇게 하면 된다고 생각합니다😂

2024-02-03 08:37 UTC, poi1649 commented on src/main/java/laddergame/controller/LadderGameController.java
> +
오호 그런 기준이 있었군요 훌륭합니다

2024-02-03 08:37 UTC, poi1649 commented on src/main/java/laddergame/controller/LadderGameController.java
> +      RungCreateDecider rungCreateDecider, LadderGenerator ladderGenerator) {
혹시 이럴 때 줄바꿈 기준이 있나요?

2024-02-03 08:37 UTC, poi1649 commented on src/test/java/laddergame/model/LadderGeneratorTest.java
> +  }
1. 맞습니다. 그래서 지금같은 형태에서는 LinkedList 사용이 더 적절해보여요!
2. 맞습니다. Mock 객체를 사용할 수도 있죠👍👍 추가로, RungCreateDecider 를 인터페이스로 만들어 decide 라는 추상 메서드만 가지게 하고, 프로덕션과 테스트에서 사용하는 코드는 따로 구현해줄수도 있어요. 두 방법의 장단점을 생각해보시고 나중에 이런 상황이 있을때 고려해보셔도 좋겠네요
```java
public interface RungCreateDecider {
  boolean decide();
}
```

```java
public class RandomRungCreateDecider implements RungCreateDecider {

  @Override
  public boolean decide() {
      ... 구현
 }
}
```

```java
public class TestRungCreateDecider implements RungCreateDecider {

  @Override
  public boolean decide() {
      ... 구현
 }
}

2024-02-03 08:37 UTC, poi1649 commented on src/test/java/laddergame/model/ladder/RungTest.java
> +  }
왜 분리안해주시죠!?

2024-02-03 08:38 UTC, poi1649 approved these changes
리뷰 반영 고생많으셨습니다. ㅋㅋㅋ 새벽에 다할줄이야..
몇가지 커멘트 더 남기긴 했는데 이건 다음 단계 진행하면서 같이 반영해주세요.
2단계도 화이팅~

2024-02-03 08:39 UTC, merged

2024-02-03 20:05 UTC, junseoplee commented on src/main/java/laddergame/controller/LadderGameController.java
> +      RungCreateDecider rungCreateDecider, LadderGenerator ladderGenerator) {
최대한 관련 있는 항목끼리 같은 라인에 있고, 깔끔하게 보이도록 합니다.
주로 80자 선에서 개행을 합니다

2024-02-03 21:46 UTC, junseoplee commented on src/test/java/laddergame/model/ladder/RungTest.java
> +  }
ㅋㅋㅋㅋㅋㅋ 했습니다!!!!!