[2단계 - 사다리 게임 실행] 이준섭 미션 제출합니다.
poi1649/java-ladder pull request #2
Opened 2024-02-08 09:55 UTC by junseoplee

2024-02-08 14:49 UTC, poi1649 requested changes
사다리 2단계도 고생 많으셨습니다. 꽤 어려운 로직인데도 요구사항 하나 빼먹은 것 없이 훌륭하게 구현해주셨네요. 👍

전반적으로 코드에 이유가 있다고 느껴져서 크게 변경을 강요할 부분은 사실 없었지만, 아직은 배우는 단계인 만큼 조금 더 세심한 부분까지 신경쓰는 것을 목표로 해봐도 좋을 것 같습니다. 그래서 이번 리뷰는 조금 소소한 부분까지 남겨봤어요.
남긴 리뷰에 더해 이번엔 `모든 원시값을 포장하는 것` 을 목표로 수정을 진행해주셨으면 합니다!

기간은 조금 넉넉하게 잡아도 좋을 것 같아요. 명절은 푹 쉬시고 명절 후 부터 열심히 하는 것으로 하죠! 
다음주 목요일 오후 6시 전까지 다시 리뷰 요청 주세요!

그럼 이만 즐거운 연휴 보내시죠~

2024-02-08 14:49 UTC, poi1649 commented on README.md
> +  -
이건 뭐죠?

2024-02-08 14:49 UTC, poi1649 commented on README.md
> +  - [x] 'all' 을 입력받는 경우 전체 참여자의 결과를 출력하고 종료한다.
이번에도 아주 꼼꼼하네요 👍👍👍👍

2024-02-08 14:49 UTC, poi1649 commented on src/main/java/laddergame/controller/LadderGameController.java
> +    Prizes prizes = receivePrizes(participants);
단수, 복수형 디테일까지 좋네요

2024-02-08 14:49 UTC, poi1649 commented on src/main/java/laddergame/model/ErrorMessage.java
> +  CONTAINS_ALL_PARTICIPANT_NAME("[ERROR] 참여자의 이름에는 'all' 이 포함될 수 없습니다."),
ㅋㅋㅋㅋㅋ💯💯💯

2024-02-08 14:49 UTC, poi1649 commented on src/main/java/laddergame/model/ladder/Rung.java
> +    return List.copyOf(hasRungAtPoints);
오... 방어적 복사 👍👍 이건 누가 알려준건가요? 어떤 이점이 있나요?

2024-02-08 14:49 UTC, poi1649 commented on src/main/java/laddergame/model/ladder/Rung.java
> +  public boolean isCurrentPointHasRung(int point) {
게터보다 아래 위치시킨 이유가 있나요?

2024-02-08 14:49 UTC, poi1649 commented on src/main/java/laddergame/model/participant/Participants.java
> +                       .findFirst()
findFirst와 findAny의 차이는 뭘까요!? 어떤 장단점이 있을까요

2024-02-08 14:49 UTC, poi1649 commented on src/main/java/laddergame/model/prize/Prize.java
> +    if (inputPrize.contains("all")) {
all 도 상수로 관리할 수 있을 것 같아요! 사람들 이름 규칙에서도 사용되기도 하고요. 현재는 관리 지점이 두 군데죠!

2024-02-08 14:49 UTC, poi1649 commented on src/main/java/laddergame/model/prize/Prizes.java
> +  public Prizes(List<Prize> prizes, Participants participants) {
개행이 빠졌군요🦅

2024-02-08 14:49 UTC, poi1649 commented on src/main/java/laddergame/view/InputView.java
> +    System.out.println("\n최대 사다리 높이는 몇 개 인가요?");
저는 \n 대신 System.lineSeparator()를 사용하는 편입니다. 개행 문자가 왜 이렇게 사용되는지 알아봐도 좋을 것 같네요!

2024-02-08 14:49 UTC, poi1649 commented on src/main/java/laddergame/view/OutputView.java
> +  }
오버로딩 적절하네요👍

2024-02-08 14:49 UTC, poi1649 commented on src/test/java/laddergame/model/LadderGeneratorTest.java
> +public class LadderGeneratorTest {
public으로 만들어주신 이유가 있나요?

2024-02-08 14:49 UTC, poi1649 commented on src/main/java/laddergame/controller/LadderGameController.java
> +    Prize prize;
prize를 여기서 따로 선언해준 이유가 있나요?

2024-02-08 14:49 UTC, poi1649 commented on src/main/java/laddergame/controller/LadderGameController.java
> +      Prize prize = resultCalculator.getPrizeFor(participant.getParticipantName());
현재 로직대로라면 출력할 때 마다 결과를 계산해야하네요. 이를 수정할 방법은 없을까요!?

2024-02-08 14:49 UTC, poi1649 commented on src/test/java/laddergame/model/ResultCalculatorTest.java
> +     */
오호ㅋㅋㅋㅋ... 왜 그리기로 마음먹으셨나요?

2024-02-08 14:49 UTC, poi1649 commented on src/main/java/laddergame/model/ResultCalculator.java
> +    return prizes.getPrize(positionOfExit);
인덱스에 의존하지 않고 참가자와 결과를 매핑시킬 수는 없을까요!?

2024-02-08 14:49 UTC, poi1649 commented on src/main/java/laddergame/model/ladder/Ladder.java
> +      position--;
매개변수를 직접 변경하고 있네요.  만약 position이 원시값이 아니고 객체였다면 어떤 일이 일어났을까요?
만약 Position을 `불변 객체`로 만든다면 어떤 장단점이 있을까요?

2024-02-13 09:57 UTC, junseoplee commented on README.md
> +  -
참여자와 결과를 보고 싶은 사람이 일치하지 않는 경우 예외 처리한다는 의미입니다.
마지막 공백 때문이라면 자동 생성된 라인이네요!

2024-02-13 10:01 UTC, junseoplee commented on src/main/java/laddergame/model/ladder/Rung.java
> +    return List.copyOf(hasRungAtPoints);
읽기 전용의 기능을 원했기 때문에 관련 메서드를 검색했습니다!
List.copyOf 메서드를 통해 보다 간결한 표현이 가능하며, 새로운 불변 리스트를 생성하여 안정성이 높아졌습니다.

2024-02-13 10:06 UTC, junseoplee commented on src/main/java/laddergame/model/ladder/Rung.java
> +  public boolean isCurrentPointHasRung(int point) {
bool 값을 반환하는 게터 메서드 이기 때문에 게터 근처에 위치시켰습니다.
코드를 읽을 때 위에서 부터 읽게되어 게터 부터는 게터 관련 메서드임을 나타내기 위해 게터보다 아래 위치시켰습니다.

2024-02-13 13:11 UTC, junseoplee commented on src/main/java/laddergame/model/participant/Participants.java
> +                       .findFirst()
findFirst는 순서가 있는 스트림에서 첫 번째 요소를 확인합니다.
findAny는 순서와 상관 없이 임의의 요소를 반환합니다. 따라서 병렬 처리에서 빠르게 찾을 수 있습니다.
이 메서드에서는 일치하는 참가자를 찾았을 경우 그 시점에서 반환해서 검색을 중단하는 것이 효율적이니 findFirst를 쓰는 것이 적합하다 생각합니다.

2024-02-13 14:14 UTC, junseoplee commented on src/main/java/laddergame/model/prize/Prize.java
> +    if (inputPrize.contains("all")) {
감사합니다!

2024-02-13 15:12 UTC, junseoplee commented on src/main/java/laddergame/view/InputView.java
> +    System.out.println("\n최대 사다리 높이는 몇 개 인가요?");
운영 체제에 따라, 버전에 따라 개행 문자가 다르기 때문에 System.lineSeparator() 메서드를 사용한다면 운영 체제에 관계없이 개행이 가능합니다.

2024-02-13 15:23 UTC, junseoplee commented on src/test/java/laddergame/model/LadderGeneratorTest.java
> +public class LadderGeneratorTest {
로컬 기록을 보니 단순 실수입니다. 수정하겠습니다.

2024-02-13 15:36 UTC, junseoplee commented on src/main/java/laddergame/controller/LadderGameController.java
> +    Prize prize;
블럭 바깥에서 사용해야한다면 이런식으로 바깥에서 선언해야합니다. 하지만 이 경우에는 안에서만 사용하기 때문에 밖에서 선언해야 할 필요는 없네요.
처음 메서드를 작성할 때 try-catch를 사용하지 않았기에 남아있는 라인입니다.
저는 try 블럭 내에서 선언하고 초기화 하도록하는게 보다 더 깔끔한 코드로 보이기에 수정하겠습니다.

2024-02-14 07:36 UTC, junseoplee commented on src/main/java/laddergame/controller/LadderGameController.java
> +      Prize prize = resultCalculator.getPrizeFor(participant.getParticipantName());
ResultCalculator 에 Map 으로 저장하는 메서드를 추가한 후 수정했습니다!

2024-02-14 07:36 UTC, junseoplee commented on src/test/java/laddergame/model/ResultCalculatorTest.java
> +     */
계속 헷갈려서..

2024-02-14 08:41 UTC, junseoplee commented on src/main/java/laddergame/model/ResultCalculator.java
> +    return prizes.getPrize(positionOfExit);
가능합니다!

2024-02-14 09:40 UTC, junseoplee commented on src/main/java/laddergame/model/ladder/Ladder.java
> +      position--;
객체는 참조도 전달되기 때문에 메서드 내에서 객체의 상태를 변경하면 호출자도 같은 객체를 참조하고 있어 오류가 발생할 수도 있습니다.
새로운 값이 필요할 때 마다 매개 변수를 직접 사용하는 것이 아니라 새로운 변수로 사용하는 방향으로 바꾸겠습니다.

2024-02-15 15:10 UTC, poi1649 requested changes
리뷰 반영해주시느라 고생많으셨습니다~ 
대체로 잘 반영해주셔서 그냥 다음 미션을 진행할까했으나 아주 조금만 더 수정해보면 좋을 것 같아 찐찐막 Request Change 드리겠습니다. 월요일 오후 6시까지 스피디하게 끝내시고 다음주에 새로운 미션 시작하시죠 🔥

2024-02-15 15:10 UTC, poi1649 commented on src/main/java/laddergame/controller/LadderGameController.java
> +    if (targetParticipant.equalsIgnoreCase(FORBIDDEN_WORD)) {
아주 403 같은 단어선택이네요𐚣

2024-02-15 15:10 UTC, poi1649 commented on src/main/java/laddergame/model/participant/Participants.java
> +                       .findFirst()
findAny같은 경우에도 먼저 타겟을 찾은 경우 검색을 중단합니다! 그래서 순서가 상관없는 지금같은 경우는 findAny가 더 효율적일 것 같아요

2024-02-15 15:10 UTC, poi1649 commented on src/main/java/laddergame/controller/LadderGameController.java
> +      Prize prize = resultCalculator.getPrizeFor(participant.getParticipantName());
만약 사다리가 커진다면 어플리케이션 초기 로딩 비용이 커질 것 같아요! 
다른 방법은 없을까요!?
(구현은 안하셔도 괜찮습니다.)

2024-02-15 15:10 UTC, poi1649 commented on src/test/java/laddergame/model/ResultCalculatorTest.java
> +     */
좋습니다 ㅋㅋㅋ 내가 헷갈리면 남도 헷갈리기떄문에 협업에선 이런 디테일이 생산성을 높이는 비결이 될 때도 있어요

2024-02-15 15:10 UTC, poi1649 commented on src/main/java/laddergame/model/ResultCalculator.java
> +    return prizes.getPrize(positionOfExit);
ㅋㅋㅋㅋ 
지금은 `Participants` 객체 안의 List에 할당된 순서에 의존해서 위치를 가져와야해서 만약 List에 묶이는 순서가 다르다면 로직에 문제가 생길 수 있어요.

사실 그럴 경우는 흔치 않겠지만 지금은 배우는 과정이니 해결할 수 있는 방법을 생각해보셔도 좋을 것 같네요

2024-02-15 15:10 UTC, poi1649 commented on src/main/java/laddergame/model/ladder/Ladder.java
> +      position--;
좋습니다! 추가로 위에서 말한 불변객체에 대해 알아보시고 적용해보셔도 좋을 것 같아요

2024-02-15 15:10 UTC, poi1649 commented on src/main/java/laddergame/model/ladder/Rung.java
> +    return List.copyOf(hasRungAtPoints);
훌륭하네요👍 
말씀해주신것처럼 List.of 를 사용하면 새로운 리스트를 생성하기 때문에, Collections.unmodifiableList 와는 다르게 원본 리스트가 수정되어도 get을 한 시점의 데이터를 그대로 전달해줄 수 있는 장점이 있어요. 

다만, 어떨 때에는 get 이후에 원본의 수정되면 수정된 내용을 포함해야할 수도 있으니 비즈니스 로직을 잘 파악해서 결정하시면 됩니다.

2024-02-18 14:05 UTC, junseoplee commented on src/main/java/laddergame/model/participant/Participants.java
> +                       .findFirst()
감사합니다!

2024-02-18 18:42 UTC, junseoplee commented on src/main/java/laddergame/controller/LadderGameController.java
> +      Prize prize = resultCalculator.getPrizeFor(participant.getParticipantName());
결과 계산 메서드에서 병렬 스트림을 생성합니다.
그 후 병렬 처리로 계산한다면 더 빠르게 할 수 있지 않을까 합니다.

추가적인 의견입니다.
이렇게 전체 결과를 출력하는 메서드가 아닌, 각 지정된 참가자의 결과를 출력하는 메서드라면
시간과 비용을 줄일 수 있다 생각합니다.
이미 계산된 Map에 저장된 결과에서 키 벨류로 가져올 수 있게 하면  중복 계산을 줄일 수 있습니다.

2024-02-22 13:48 UTC, poi1649 approved these changes
반영 고생하셨습니다. 사다리는 여기까지 하죠! 
approve & merge 합니다~

2024-02-22 13:48 UTC, merged